# config for analysis


# most CPUs to ever use at once
max_cpus: 8

# amplicons sequenced by PacBio
amplicons_PDCoV: data/PacBio_amplicon_PDCoV.gb
amplicons_panDCoV: data/PacBio_amplicon_panDCoV.gb

# how to parse the amplicon
feature_parse_specs_PDCoV: data/feature_parse_specs_PDCoV.yaml
feature_parse_specs_panDCoV: data/feature_parse_specs_panDCoV.yaml

# do we get the sequencing data from the 'local' server or 'SRA'?
seqdata_source: local

# list of PacBio sequencing runs linking barcodes to variants
pacbio_runs: data/PacBio_runs.csv

# list of Illumina sequencing runs of barcodes
barcode_runs: data/barcode_runs.csv

# wildtype sequence of mutagenized gene
wildtype_sequence: data/wildtype_sequence.fasta
site_number_offset: 302  # add this to sequential sites to get PDCoV RBD numbering

#delta-cov alignment
dcov_alignment: data/dcov_RBD_aligned.fasta

# pdbs for mapping, analysis


# URLs from which we download binding & expression of mutants & variants and surveillance count data



# output directories / files
summary_dir: results/summary
figs_dir: results/figures
ccs_dir: results/ccs
process_ccs_dir: results/process_ccs
processed_ccs_file_PDCoV: results/process_ccs/processed_ccs_PDCoV.csv
processed_ccs_file_panDCoV: results/process_ccs/processed_ccs_panDCoV.csv
variants_dir: results/variants
nt_variant_table_file_PDCoV: results/variants/nucleotide_variant_table_PDCoV.csv
nt_variant_table_file_panDCoV: results/variants/nucleotide_variant_table_panDCoV.csv
codon_variant_table_file_PDCoV: results/variants/codon_variant_table_PDCoV.csv
codon_variant_table_file_panDCoV: results/variants/codon_variant_table_panDCoV.csv
counts_dir: results/counts
variant_counts_file: results/counts/variant_counts.csv
expression_sortseq_dir: results/expression_meanF
expression_sortseq_file: results/expression_meanF/bc_expression.csv
binding_scores_dir: results/binding_scores
gAPN_Kds_file: results/binding_scores/gAPN_bc_binding.csv
hAPN_meanF_file: results/binding_scores/hAPN_bc_binding.csv
pAPN_meanF_file: results/binding_scores/pAPN_bc_binding.csv
final_variant_scores_dir: results/final_variant_scores
final_variant_scores_mut_file: results/final_variant_scores/final_variant_scores.csv
epistatic_shifts_dir: results/epistatic_shifts
JSD_v_WH1_file: results/epistatic_shifts/JSD_versus_Wuhan1_by_target.csv
JSD_v_WH1_expr_file: results/epistatic_shifts/JSD_versus_Wuhan1_EXPRESSION_by_target.csv

alignment_diversity_dir: results/dcov_alignment_diversity

visualization_dir: docs/_includes


# parameters for running PacBio `ccs` program
min_ccs_accuracy: 0.999
min_ccs_passes: 3
min_ccs_length: 50
max_ccs_length: 5000

# max error rate in gene / barcode CCSs retained for consensu building
max_error_rate: 0.0001

# Parameters for processing Illumina barcodes, assuming this structure:
#  [R2 binds] - [upstream] - [barcode] - [downstream] - [R1 binds]
#  This orientation is hard-wired in the barcode parser, but here it is opposite
#  Therefore, supplied the "downstream" sequence as reverse complemented upstream
# Passed to `dms_variants.illuminabarcodeparser.IlluminaBarcodeParser`:
illumina_barcode_parser_params:
  upstream: GGCCGC
  downstream: ''
  minq: 20
  upstream_mismatch: 1
  downstream_mismatch: 0

# Input files for analyses from the data subdirectory
RBD_sites: data/RBD_sites.csv
