name: PDCoV_RBD_DMS
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - altair=4.2
  - biopython=1.79
  - entrez-direct=13.9
  - git-lfs
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyterlab
  - minimap2=2.18
  - natsort
  - nodejs
  - pbccs=6.0.0
  - pip
  - python=3.8
  - seaborn=0.11.1
  - snakemake=6.2.1
  - sra-tools=2.10.9
  - ete3
  - pip:
    - alignparse==0.6.0
    - dms-variants==1.4.2
    - neutcurve
    - openpyxl
